project:
  type: website
  output-dir: docs

website:
  title: "Gab Chen - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: weekly-notes/week-01-notes.qmd
        text: Weekly Notes
          - text: Labs
        menu:
          - href: lab/lab_0/index.qmd
            text: "Lab 0: dplyr Basics"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
