project:
  type: website
  output-dir: docs

website:
  title: "Gab Chen - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      -text: Weekly Notes
      menu:
        -href: weekly-notes/week-010notes.qmd
        text: Week 1

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
